version: '3.9'
services:
  labeldetector:
    environment:
      AWS_ACCESS_KEY_ID: ${{ REPLACE }}
      AWS_SECRET_ACCESS_KEY: ${{ REPLACE }}
      AWS_REGION: eu-west-2
    image: nicrausaz/labeldetector:latest
    ports:
      - "8080:8080"
  dataobject:
    environment:
      AWS_BUCKET_NAME: amt.team10.diduno.education
      AWS_ACCESS_KEY_ID: ${{ REPLACE }}
      AWS_SECRET_ACCESS_KEY: ${{ REPLACE }}
      AWS_REGION: eu-west-2
      PUBLIC_LINK_VALIDITY_DURATION: 60
    image: nicrausaz/dataobject:latest
    ports:
      - "8081:8080"
